spring:
    application:
        name: nice

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    level:
        org:
            springframework:
                web: DEBUG


management:
    tracing:
        propagation:
            type: w3c
        enabled: true
        sampling:
            probability: 1.0
        zipkin:
            enable: true
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans